### ISSUE TITLE
Re-Indexing in Obsidian Live Mode doesn't work at page bottom

### ISSUE THREAD

**Issue by adueck11** [charliecm/obsidian-tidy-footnotes#3]
I've put footnotes in the indexed order: 

![grafik](https://user-images.githubusercontent.com/59452072/148213883-e0a4cfc9-1477-427b-9a88-6b55e526af6d.png)

After runnig the command "Tidy Footnotes" the index is changed correctly in the text, but not at the bottom of the page: 

![grafik](https://user-images.githubusercontent.com/59452072/148213918-2ed77364-99d4-4c5f-a5df-ed77b0399241.png)

Obsidian 0.13.14

**Comment by charliecm** [comment]
@adueck11 Thanks for reporting. I'm unable to reproduce it. Can you try the plugin again using Obsidian 0.13.19 (just released today)?

**Comment by adueck11** [comment]
Sorry, my fault :see_no_evil: At the bottom I had the footnotes wrong: instead of [^1] I wrote [1] only. 

Thank you for your plugin! :+1:
